- name: Build Frontend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./project/frontend

    - name: Build Backend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./project/backend

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend